/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import javax.swing.JFrame;


/**
 *
 * @author wardati
 */
public class menu_utamaadmin extends javax.swing.JFrame {

    /**
     * Creates new form menu_utamaadmin
     */
    PanelUser pu;
    panelbarang pb; 
    panelriwayat pr;
    panellaba pl;
    public menu_utamaadmin() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        panel_master.show(false);
        panel_transaksi.show(false);
        panel_laporan.show(false);
        
        pu = new PanelUser();
        mainpanel.add(pu);
        pu.setVisible(false);
        
        pb = new panelbarang();
        mainpanel.add(pb);
        pb.setVisible(false);
        
        pr = new panelriwayat();
        mainpanel.add(pr);
        pr.setVisible(false);
        
        pl = new panellaba();
        mainpanel.add(pl);
        pl.setVisible(false);
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bt_home = new javax.swing.JButton();
        bt_master = new javax.swing.JButton();
        bt_transaksi = new javax.swing.JButton();
        bt_laporan = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        panel_master = new javax.swing.JPanel();
        bt_user = new javax.swing.JButton();
        bt_barang = new javax.swing.JButton();
        panel_transaksi = new javax.swing.JPanel();
        bt_riwayat = new javax.swing.JButton();
        panel_laporan = new javax.swing.JPanel();
        bt_laba = new javax.swing.JButton();
        mainpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 51, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_hitam-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 51, 0));

        jPanel5.setBackground(new java.awt.Color(204, 51, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Santoso Jaya Makmur");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(361, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(254, 194, 96));

        bt_home.setBackground(new java.awt.Color(204, 51, 0));
        bt_home.setFont(new java.awt.Font("Eras Demi ITC", 0, 16)); // NOI18N
        bt_home.setForeground(new java.awt.Color(255, 255, 255));
        bt_home.setText("Home");
        bt_home.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        bt_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_homeMouseClicked(evt);
            }
        });
        bt_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_homeActionPerformed(evt);
            }
        });

        bt_master.setBackground(new java.awt.Color(204, 51, 0));
        bt_master.setFont(new java.awt.Font("Eras Demi ITC", 0, 16)); // NOI18N
        bt_master.setForeground(new java.awt.Color(255, 255, 255));
        bt_master.setText("Master");
        bt_master.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        bt_master.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_masterMouseClicked(evt);
            }
        });
        bt_master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_masterActionPerformed(evt);
            }
        });

        bt_transaksi.setBackground(new java.awt.Color(204, 51, 0));
        bt_transaksi.setFont(new java.awt.Font("Eras Demi ITC", 0, 16)); // NOI18N
        bt_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        bt_transaksi.setText("Transaksi");
        bt_transaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        bt_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_transaksiMouseClicked(evt);
            }
        });
        bt_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_transaksiActionPerformed(evt);
            }
        });

        bt_laporan.setBackground(new java.awt.Color(204, 51, 0));
        bt_laporan.setFont(new java.awt.Font("Eras Demi ITC", 0, 16)); // NOI18N
        bt_laporan.setForeground(new java.awt.Color(255, 255, 255));
        bt_laporan.setText("Laporan");
        bt_laporan.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        bt_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_laporanMouseClicked(evt);
            }
        });
        bt_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_laporanActionPerformed(evt);
            }
        });

        jButton5.setText("Logout");

        panel_master.setBackground(new java.awt.Color(254, 194, 96));

        bt_user.setBackground(new java.awt.Color(204, 51, 0));
        bt_user.setFont(new java.awt.Font("Eras Demi ITC", 0, 16)); // NOI18N
        bt_user.setForeground(new java.awt.Color(255, 255, 255));
        bt_user.setText("User");
        bt_user.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        bt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_userActionPerformed(evt);
            }
        });

        bt_barang.setBackground(new java.awt.Color(204, 51, 0));
        bt_barang.setFont(new java.awt.Font("Eras Demi ITC", 0, 16)); // NOI18N
        bt_barang.setForeground(new java.awt.Color(255, 255, 255));
        bt_barang.setText("Barang");
        bt_barang.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        bt_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_barangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_masterLayout = new javax.swing.GroupLayout(panel_master);
        panel_master.setLayout(panel_masterLayout);
        panel_masterLayout.setHorizontalGroup(
            panel_masterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_barang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
            .addComponent(bt_user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_masterLayout.setVerticalGroup(
            panel_masterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_masterLayout.createSequentialGroup()
                .addComponent(bt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_transaksi.setBackground(new java.awt.Color(254, 194, 96));

        bt_riwayat.setBackground(new java.awt.Color(204, 51, 0));
        bt_riwayat.setFont(new java.awt.Font("Eras Demi ITC", 0, 16)); // NOI18N
        bt_riwayat.setForeground(new java.awt.Color(255, 255, 255));
        bt_riwayat.setText("Riwayat");
        bt_riwayat.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        bt_riwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_riwayatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_transaksiLayout = new javax.swing.GroupLayout(panel_transaksi);
        panel_transaksi.setLayout(panel_transaksiLayout);
        panel_transaksiLayout.setHorizontalGroup(
            panel_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_riwayat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        );
        panel_transaksiLayout.setVerticalGroup(
            panel_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_riwayat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        panel_laporan.setBackground(new java.awt.Color(254, 194, 96));

        bt_laba.setBackground(new java.awt.Color(204, 51, 0));
        bt_laba.setFont(new java.awt.Font("Eras Demi ITC", 0, 16)); // NOI18N
        bt_laba.setForeground(new java.awt.Color(255, 255, 255));
        bt_laba.setText("Laba");
        bt_laba.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        bt_laba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_labaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_laporanLayout = new javax.swing.GroupLayout(panel_laporan);
        panel_laporan.setLayout(panel_laporanLayout);
        panel_laporanLayout.setHorizontalGroup(
            panel_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_laporanLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_laba, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_laporanLayout.setVerticalGroup(
            panel_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_laba, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bt_home, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bt_master, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(bt_laporan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_transaksi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panel_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_master, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(bt_home, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_master, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_master, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainpanel.setBackground(new java.awt.Color(254, 194, 96));
        mainpanel.setLayout(new javax.swing.BoxLayout(mainpanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_homeActionPerformed
        // TODO add your handling code here:
        //menyembunyikan semua panel untuk menampilkan mainpanel
        pb.setVisible(false);
        pu.setVisible(false);
        pr.setVisible(false);
        pl.setVisible(false);
    }//GEN-LAST:event_bt_homeActionPerformed

    private void bt_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_transaksiActionPerformed

    private void bt_masterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_masterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_masterActionPerformed

    private void bt_masterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_masterMouseClicked
        //menampilkan button pada master
        panel_master.show(true);
        panel_master.repaint();
        panel_master.revalidate();
        //menghide button lain
        panel_transaksi.show(false);
        panel_laporan.show(false);
    }//GEN-LAST:event_bt_masterMouseClicked

    private void bt_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_transaksiMouseClicked
        //menampilkan button pada transaksi
        panel_transaksi.show(true);
        panel_transaksi.repaint();
        panel_transaksi.revalidate();
        //menghide button lain
        panel_master.show(false);
        panel_laporan.show(false);
    }//GEN-LAST:event_bt_transaksiMouseClicked

    private void bt_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_laporanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bt_laporanActionPerformed

    private void bt_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_laporanMouseClicked
        // TODO add your handling code here:
        //menampilkan button pada laporan
        panel_laporan.show(true);
        panel_laporan.repaint();
        panel_laporan.revalidate();
        //menghide button lain
        panel_master.show(false);
        panel_transaksi.show(false);
    }//GEN-LAST:event_bt_laporanMouseClicked

    private void bt_riwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_riwayatActionPerformed
        // TODO add your handling code here:
        //menampilkan panel riwayat
        pr.setVisible(true);
        pb.setVisible(false);
        pu.setVisible(false);
        pl.setVisible(false);
    }//GEN-LAST:event_bt_riwayatActionPerformed

    private void bt_labaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_labaActionPerformed
        // TODO add your handling code here:
        //menmapilkan panel laba
        pl.setVisible(true);
        pu.setVisible(false);
        pb.setVisible(false);
        pr.setVisible(false);
    }//GEN-LAST:event_bt_labaActionPerformed

    private void bt_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_barangActionPerformed
        //menampilkan panel barang
        pb.setVisible(true);
        pu.setVisible(false);
        pr.setVisible(false);
        pl.setVisible(false);
    }//GEN-LAST:event_bt_barangActionPerformed

    private void bt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_userActionPerformed
        // TODO add your handling code here:
        //user
        pu.setVisible(true);
        pb.setVisible(false);
        pr.setVisible(false);
        pl.setVisible(false);
    }//GEN-LAST:event_bt_userActionPerformed

    private void bt_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_homeMouseClicked
        // menghide semua button
        panel_master.show(false);
        panel_transaksi.show(false);
        panel_laporan.show(false);
    }//GEN-LAST:event_bt_homeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_utamaadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_utamaadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_utamaadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_utamaadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_utamaadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_barang;
    private javax.swing.JButton bt_home;
    private javax.swing.JButton bt_laba;
    private javax.swing.JButton bt_laporan;
    private javax.swing.JButton bt_master;
    private javax.swing.JButton bt_riwayat;
    private javax.swing.JButton bt_transaksi;
    private javax.swing.JButton bt_user;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel panel_laporan;
    private javax.swing.JPanel panel_master;
    private javax.swing.JPanel panel_transaksi;
    // End of variables declaration//GEN-END:variables
}
